[package]
name = "dataplane-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true


[dependencies]
serde.workspace=true
serde_json.workspace=true
bon.workspace=true
chrono.workspace=true

[lints]
workspace = true
